### ISSUE TITLE
Binding of Isaac + Wrath of the Lamb DRM free not imported

### ISSUE THREAD

**Issue by matteobaire** [UncleGoogle/galaxy-integration-humblebundle#103]
**Describe the bug**
Binding of Isaac + Wrath of the Lamb DRM free version not imported in Galaxy 2.0

**Expected behavior**
Binding of Isaac + Wrath of the Lamb should be imported the same way it happens to all other DRM free games from my Humble Bundle Library

**Plugin installed**
directly from Galaxy
[plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/4553346/plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.zip)

**Provide logs**

no file named plugin-humble-numbers.1

**Comment by UncleGoogle** [comment]
Hi, from logs I see this game is properly sent from plugin to Galaxy. 

So the issue is with Galaxy gamesDB. Please create report for Galaxy asking for unspam this product: 

```
game_id: bindingofisaac_dlc
game_title: The Binding of Isaac + Wrath of the Lamb DLC 
```

as it is valid game that should be downloadable and contains this DLC inside.

**Comment by matteobaire** [comment]
OK, thanks. I'll send a report to Galaxy.
