### ISSUE TITLE
Do not add to list non-games (i.e. software or comic books)

### ISSUE THREAD

**Issue by PastorGL** [UncleGoogle/galaxy-integration-humblebundle#11]
I bought a number of software bundles, and now I have, for example, ACDSee and Aurora HDR in the game list (among others):

![image](https://user-images.githubusercontent.com/738397/62171049-b22abb80-b33e-11e9-8360-8c427af92f9c.png)

If I click a non-game, the Overview screen looks like this:

![image](https://user-images.githubusercontent.com/738397/62171097-e56d4a80-b33e-11e9-8c04-f8a9abb2f70c.png)

Not very useful %)

**Comment by UncleGoogle** [comment]
Thanks for report. Looks like Galaxy games database is curated manually, so you probably won't see all non-games after some time.

Anyway, I'll keep this issue open, to check for a way to do it in a free time. Currently there is quite dummy check to exclude only items that have no direct downloads for windows, mac or linux... 

@PastorGL could you check this StudioUltimate json data?

- open devtools
- click on Network tab
- nagivate to https://www.humblebundle.com/home/library
- click on after one on requests of name like on image below
- search for product name (Photo Studio..) in Response subtab

![39055cc457338616633fa89f1ed95a38](https://user-images.githubusercontent.com/12197825/62280139-a2e56400-b44b-11e9-907b-c085dc2c0aa4.png)

- if found, copy whole response content and paste here on in a file. There is no sensitive data beside amount of spend $ so you can remove it

**Comment by PastorGL** [comment]
It was a 'Humble Software Bundle: Professional Photography': [1.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3458346/1.zip)

Huh, it was a bit hard to find the right request. Never realized that I've acquired 44 bundles through the years, htat's quite a number.

**Comment by UncleGoogle** [comment]
@PastorGL 
could you check this build logs? Ignored entries should be logged like that:
`Ignoring xxx due to bundle type: yyy`

GOG Galaxy games db has it own filter, but in case any new strange non-game item isn't catch there the plugin should filter it out first.

[humblebundle_0.3.2.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3526549/humblebundle_0.3.2.zip)

**Comment by PastorGL** [comment]
@UncleGoogle yes, there are log records like
`2019-08-21 22:41:07,998 - root - DEBUG - Ignoring vegasproevenmore_softwarebundle due bundle type: softwarebundle
2019-08-21 22:41:08,000 - root - DEBUG - Ignoring professionalphotography_softwarebundle due bundle type: softwarebundle`
and programs no more appear in the list.

Thank you!

**Comment by UncleGoogle** [comment]
Thanks for testing. Changes merged, but it will be deployed in 0.4 release (https://github.com/UncleGoogle/galaxy-integration-humblebundle/milestone/3)
