### ISSUE TITLE
Humble games not showing up

### ISSUE THREAD

**Issue by R160K** [UncleGoogle/galaxy-integration-humblebundle#110]
**Describe the bug**
Have connected to Humble Bundle three times now, with drm-free, trove and keys checked (plus once with only drm-free checked), and not only are no games showing up (neither under owned games nor subscriptions), but a game I own on Steam that is not a Humble Bundle game shows up. Have tried Sync Integrations multiple times, as well as exiting and restarting the Galaxy app, to no avail.
![Screenshot](https://user-images.githubusercontent.com/5496317/82374270-b67fac80-9a16-11ea-8c61-505297512edd.png)

**Expected behaviour**
I expected the games to show up.

**Plugin installed**
directly from Galaxy

**Provide logs**
[plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/4652920/plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log)

**Comment by UncleGoogle** [comment]
Hi @R160K, your log tell me that you have only one order on humble:
https://www.humblebundle.com/downloads?key=wADTkmhuBDeT8XEZ

The steam on the screen is valid DRM-free game from above link

If that is not true, and you have bought more on humble, please paste screenshot from https://www.humblebundle.com/home/library

Trove games won't show if you were never subscriber.

**Comment by R160K** [comment]
My bad, just worked out my Humble Bundle subscription is linked to my Google account, not that e-mail address. I must have made that account years ago and forgotten about it (I think I did purchase that game on the Humble Store years ago). Have reconnected using my Google login and all is working well. Apologies for the waste of time.
