### ISSUE TITLE
Not able to connect too humble drm free games of my account anymore:

### ISSUE THREAD

**Issue by darksgan** [UncleGoogle/galaxy-integration-humblebundle#111]
**Describe the bug**
A clear and concise description of what the bug is. Provide steps to reproduce.

**Expected behavior**

**Plugin installed**
directly from Galaxy / manually from your repository releases

**Provide logs**
- make reproduction steps you described above (tip: _cogwheel menu -> Sync Integration_ refreshes owned and local games)
- go to logs location:
    - (Windows) %programdata%\GOG.com\Galaxy\logs
    - (macOS)  /Users/Shared/GOG.com/Galaxy/Logs
- archive logs to zip/7z file; in most cases those two logs will be sufficient:
    - `plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log.txt`
    - `plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log.1`
- attach archive in bug report

**Comment by UncleGoogle** [comment]
#112
