### ISSUE TITLE
Not able to connect too humble drm-free games of my account anymore: I get something like "Se ha denegado el acceso a dl.humble.com" (Access Denied to dl.humble.com)

### ISSUE THREAD

**Issue by darksgan** [UncleGoogle/galaxy-integration-humblebundle#112]
**Describe the bug**
A clear and concise description of what the bug is. Provide steps to reproduce.

**Expected behavior**

**Plugin installed**
directly from Galaxy / manually from your repository releases

**Provide logs**
- make reproduction steps you described above (tip: _cogwheel menu -> Sync Integration_ refreshes owned and local games)
- go to logs location:
    - (Windows) %programdata%\GOG.com\Galaxy\logs
    - (macOS)  /Users/Shared/GOG.com/Galaxy/Logs
- archive logs to zip/7z file; in most cases those two logs will be sufficient:
    - `plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log.txt`
    - `plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log.1`
- attach archive in bug report

**Comment by UncleGoogle** [comment]
Hi @darksgan 

you probably forgot to fill the issue template.

I can still login to humble. Where you see "Se ha denegado el acceso a dl.humble.com"? Please paste logs and give a screenshot

**Comment by waden34** [comment]
I too am seeing this error. 

I can log in to my Humble account and download games from my Library.

From within Galaxy, if you click on the Install button for a DRM game, Galaxy opens a link in the browser to download the game. That link results in a 403 error:

Access to dl.humble.com was denied
You don't have authorization to view this page.
HTTP ERROR 403

The TTL & T query parameters in the link are different from a working link straight from the Humble Bundle site.

This working link came from my Humble library:
https://dl.humble.com/Anomaly_Korea_Setup_1371072846.zip?gamekey=7azW2CPfnMXadKuf&ttl=1590360950&t=66751031637937b8342b21305e35c832

This link that Galaxy spawned did not work:
https://dl.humble.com/Anomaly_Korea_Setup_1371072846.zip?gamekey=7azW2CPfnMXadKuf&ttl=1590131453&t=023353f293f6e11d436135b443f4a7c8

**Comment by UncleGoogle** [comment]
Ah, now understand.

Yes, it is known, already fixed but now released yet. Try with this: https://github.com/UncleGoogle/galaxy-integration-humblebundle/releases/tag/v0.8.0-alpha

**Comment by waden34** [comment]
Cool. The new v.8.0 version worked for me.

**Comment by darksgan** [comment]
Sorry for my late answer, I forgot to look at this again.

But, indeed, with the new 0.8.0 version, it works perfectly fine :)

Thanks and regards.
