### ISSUE TITLE
Humble Bundle subscription options not showing up in galaxy->settings->features->HUMBLE BUNDLE

### ISSUE THREAD

**Issue by nullnetworks** [UncleGoogle/galaxy-integration-humblebundle#142]
The only entry there for me is 'Metadata'. Nothing at all shows up when I filter for 'Humble Bundle' 'Subscriptions', not even the trove games.

**Comment by idbrii** [comment]
@nullnetworks Did you do something that fixed this?

I uninstalled and installed this plugin (after not using GOG for a while) because 0.9.4 said it needed reconnection and still see:

> ![GOG_Humble_bug](https://user-images.githubusercontent.com/22747334/92308302-fbffbf80-ef9c-11ea-9572-158a37df89f9.jpg)

Currently a Humble Choice Classic subscriber.

Several galaxy restarts and plugin reinstalls and no change.
