### ISSUE TITLE
Do not see options in the 'features' setting page - does not sync trove games

### ISSUE THREAD

**Issue by thefunkygibbon** [UncleGoogle/galaxy-integration-humblebundle#143]
**Describe the bug**
install guide shows that it should see list of humble choice months and trove

**Expected behavior**
to see the options and the games in GOG

**Plugin installed**
latest version automatically via gui.  also manually installed
[plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/5661455/plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log)

**Provide logs**
- make reproduction steps you described above (tip: _cogwheel menu -> Sync Integration_ refreshes owned and local games)
- go to logs location:
    - (Windows) %programdata%\GOG.com\Galaxy\logs
    - (macOS)  /Users/Shared/GOG.com/Galaxy/Logs
- archive logs to zip/7z file; in most cases those two logs will be sufficient:
    - `plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log.txt`
    - `plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log.1`
- attach archive in bug report

**Comment by UncleGoogle** [comment]
Should work fine in 9.2. Trove option in plugin GUI was dropped as per support in Galaxy _options -> Features_
Also - it should detect automatically for you.

@thefunkygibbon do you confirm it works for you now?

**Comment by UncleGoogle** [comment]
I'm closing as a stale issue (and I'm pretty sure it is already fixed). In case not - feel free to reopen
