### ISSUE TITLE
Some games with Humble Bundle do not appear on GOG Galaxy

### ISSUE THREAD

**Issue by Korb** [UncleGoogle/galaxy-integration-humblebundle#144]
**Describe the bug**
Humble Bundle:
1. Amnesia Collection
2. Ashes of the Singularity: Escalation
3. Caffeine
4. Heroes of Might & Magic III – HD Edition
5. Humble Weekly Bundle: Play and Create with GameMaker
6. Stealth Inc 2: A Game of Clones: Humble Deluxe Edition
7. Vikings - Wolves of Midgard

GOG Galaxy 2.036 beta:
1. Ashes of the Singularity: Escalation (Steam)
2. Caffeine
3. L'Abhayedes Morts
4. Might & Magic Heroes III: HD (Steam)
5. SpelunkyClassic
6. Vikings: Wolves of Midgard

![2020-12-25_17-39-06](https://user-images.githubusercontent.com/3509797/103137247-49cd3e80-46d8-11eb-8048-f0922e34694f.png)
![2020-12-25_17-40-07](https://user-images.githubusercontent.com/3509797/103137248-4a65d500-46d8-11eb-90c2-56457cd075e0.png)

Microsoft Windows 10.0.19042.685

**Expected behavior**
The lists of apps on the Humble Bundle website and on the GOG Galaxy app after selecting "Humble Bundle games only" should match.

**Plugin installed**
directly from Galaxy

**Provide logs**
[plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log](https://docs.google.com/document/d/1T53927jR-AZ5Yh9GLiiL91aBXjykwTHa2LyyQUi764s/edit)

**Comment by UncleGoogle** [comment]
Hey @Korb 

you cannot compare "Purchases" list with the products list. Please show what your "Library" bookmark in humble contains.

From plugin logs I can see that those items was parsed from humble API:
```
[
<Subproduct> Caffeine : caffeine,
<Subproduct> L'Abbaye des Morts : labbayedesmorts,
<Subproduct> Spelunky Classic Source : spelunky_classic_source,
<Subproduct> L'Abbaye des Morts Source : labbayedesmorts_source,
<Subproduct> Spelunky Classic : spelunky_classic,
<KeyGame> Ashes of the Singularity: Escalation (Steam) : ashesofthesingularity_escalation_freegame_steam
]
```
(subproducs are DRM free items to download)

Those 2:
- Humble Weekly Bundle: Play and Create with GameMaker
- Stealth Inc 2: A Game of Clones: Humble Deluxe Edition
are quite old purchases. I'm interested to see how the old orders looks like. Maybe I'm missing something. Could you please look through those when you're logged in into your account:

https://www.humblebundle.com//api/v1/order/3C74feC8YeS4yuH2
https://www.humblebundle.com//api/v1/order/5aWhP5VwydF5Dpym
https://www.humblebundle.com//api/v1/order/pZVcAburF2BT3FZd
https://www.humblebundle.com//api/v1/order/6WR4y8E3cNARrVeu
https://www.humblebundle.com//api/v1/order/xTxvsMdBEVzMwSRd
https://www.humblebundle.com//api/v1/order/scGhCRwtFqNG76UT
https://www.humblebundle.com//api/v1/order/Ssq4hac6yer6pRUh

to find those 2 items and paste what is there? WARNING: you may want to remove sensitive data (revealed keys) if any

**Comment by UncleGoogle** [comment]
@Korb friendly remainder :)

**Comment by Bertaz** [comment]
I too have old orders, tell me what you need about them

**Logs:** [pluginHumbleLogs144.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/6054424/pluginHumbleLogs144.zip)

![oldestPurchases](https://user-images.githubusercontent.com/44445647/109386766-48e5a280-78fd-11eb-9f72-d6a197b1b95e.png)

**Comment by Korb** [comment]
> friendly remainder :)

Sorry, I haven't received any notifications from Github. In Humble Library, I only see five applications:

- Caffeine
- L'Abbaye des Morts
- Might & Magic Heroes III: HD
- Spelunky Classic
- Vikings - Wolves of Midgard

Issue can be closed?
![Humble Library](https://user-images.githubusercontent.com/3509797/110213703-2a117e00-7eb2-11eb-8b1c-f66b2e21e8ea.png)

**Comment by UncleGoogle** [comment]
> Issue can be closed?

Yup, I think so. Thanks for checking it out.

@Bertaz just describe what is the exact problem in your case in seprate issue (that is always the best way to go). Which games are missing? And the same apply - compare your Library page on humble (and Keys) with the Galaxy conenent. I guess for old stuff like "Humble Jumbo Bundle 9" there may be some trickery, but lets find out what is missing first.
