### ISSUE TITLE
Humble Choice games listed as all the others.

### ISSUE THREAD

**Issue by nosyn00b** [UncleGoogle/galaxy-integration-humblebundle#147]
I'd like to have an option to have all Humble Games that are part of an Humbel Choice listed with all the others under Humble-Bundle" list, as they were simply owned games. Redeemd games should not be listed (currently also redeemed games are listed in subscriptions, I think by design)

**Comment by UncleGoogle** [comment]
Hello. So you claim that deselection of "show reveled keys" option does not work for you? Does it overlap with https://github.com/UncleGoogle/galaxy-integration-humblebundle/issues/123 ?

**Comment by nosyn00b** [comment]
Thanks UG for the clarification about the three possible states and showing only 2+3 games on "owned games". Simply Billiant. 

I wrongly supposed that all games part of a subscription was shown in subscriptions even in 2 & 3 state! I will check better the behavoiur for case 3  when subscriptions get back to work for me (currently for some reason no subscription games apart the trove are shown and also no option is shown in the settings ). Will give a peek forking....

In any case my request was to have an option to have the games with state 1 in the list of the owned games, so that they can be searchable and displayed with all the others owned games, perhapse with a dedicated "subscription" tag.

**Comment by UncleGoogle** [comment]
ok, I see. Perhaps games with state 1 ARE searchable in the current implementation

![image](https://user-images.githubusercontent.com/12197825/106331180-bcf04480-6284-11eb-9eaa-56efe0f913b3.png)

(surpassingly even as "Owned games" despite they are returned as subscription game and NOT as owned game)

But is guess they are not dispalying for you becasue of #146

**Comment by nosyn00b** [comment]
I dicovered that you can create an  "All games" collection, selecting both filters owned and subscriptions 
![image](https://user-images.githubusercontent.com/77177410/106529888-88ca8d00-64eb-11eb-96e2-3c55ff4ddc9b.png)
so you can search  all your games in a single list as I wanted (no total games counter but it does not matter)!

**Comment by UncleGoogle** [comment]
Oh nice worth added to FAQ in readme. If you could make PR would be awesome.

Subscription interface returns all: 1,2,3 + extraxes OR only 2,3 +extraxes if you have no choices left in current month.

Subscription games may not be 1:1 with owned choices returned by humble api. The latter may contain more products/keys, the former is just like scrapping the choce month.

**Comment by nosyn00b** [comment]
Ok, I'll PR with a new FAQ chapter in readme asap. 

Thanks!

PS: I confirm that in my case deselection of "show reveled keys" does not work for choice, I always see status 3 games in the list in choice.

**Comment by UncleGoogle** [comment]
> PS: I confirm that in my case deselection of "show reveled keys" does not work for choice, I always see status 3 games in the list in choice.

yeah, it does not work Choice games shown in Subscription tab. It need design rethinking, as this option is misleading.

**Comment by nosyn00b** [comment]
Hi.

I updated the readme with a FAQ section (see PR), but i saw you're using gyazo as image source, an the gyazo client gives me virus warning (most probably is a false positive).

Anyway I think using an internal resource reference to the repository content is the most clean way to refer images in the readme files, even if has the drawback of increasing your repository size (Have a look at my Fanatical repository to see what i mean)

I temporarly used the images on this issue as image source.  For example the following one.

![image](https://user-images.githubusercontent.com/77177410/106821639-d7a82c00-667d-11eb-9ee4-9d15628468fe.png)

Let me know what you think on this (having mixed image reference type is not very elegant).

**Comment by UncleGoogle** [comment]
totally agree, spawned issue to not forget

**Comment by UncleGoogle** [comment]
Ok, so in the future it would be nice to have additional filter in humble setting window that allows to:
- hide choices with already revealed keys

So either by adding filter option to modify "subscription" games (Galaxy restart needed, no live changes possible)

OR 

by allowing to return not chosen, potential games (type 1) from "owned games" AND mock them to have unrevealed keys.

I like the first option more, as second would have to do some messy hacks with game types.

**Comment by nosyn00b** [comment]
Could't you simply ignore (not passing the single games to GOG) if the the game is in status 3 and  "show reveled keys" is not flagged?

**Comment by nosyn00b** [comment]
Considering the addition in the FAQ section, this specific issue can be closed, if you agree. While  "hide choices with already revealed keys" considerations could be raised as a different thread/issue, but I think there is already another one somewhere!

**Comment by UncleGoogle** [comment]
> Could't you simply ignore (not passing the single games to GOG) if the the game is in status 3 and "show reveled keys" is not flagged?

I do that already in `get_owned_games` interface. The game is still visible in Galaxy because it is returned from `get_subscription_games` interface.

In the second interface I have no information about keys state.

But yes, those interfaces could theoretically depend on each other using cached games from one of them, something like:
```python
def get_subscription_games(self, subscription_name):
    sub_games = ...

    if not self._settings.show_revealed_keys:
        revealed_key_games = [g.machine_name for g in self._owned_games if isinstance(g, Key) and g.key_val]
        yield [game in sub_games if game.machine_name not in revealed_key_games]
    else
        yield sub_games
```

that's one idea. I don't remember why I didn't want to go that direction, need to recap potencial drawbacks.. otherwise that's briliant and can be used to fix #123

**Comment by UncleGoogle** [comment]
> Considering the addition in the FAQ section, this specific issue can be closed, if you agree. While "hide choices with already revealed keys" considerations could be raised as a different thread/issue, but I think there is already another one somewhere!

right, let me close this one.

**Comment by nosyn00b** [comment]
> In the second interface I have no information about keys state.

perhaps you can understand status of the games looking for it in the events collection
