### ISSUE TITLE
Change readme images to internal repo links

### ISSUE THREAD

**Issue by UncleGoogle** [UncleGoogle/galaxy-integration-humblebundle#150]
I updated the readme with a FAQ section (see PR), but i saw you're using gyazo as image source, an the gyazo client gives me virus warning (most probably is a false positive).

Anyway I think using an internal resource reference to the repository content is the most clean way to refer images in the readme files, even if has the drawback of increasing your repository size (Have a look at my Fanatical repository to see what i mean)

I temporarly used the images on this issue as image source.  For example the following one.

![image](https://user-images.githubusercontent.com/77177410/106821639-d7a82c00-667d-11eb-9ee4-9d15628468fe.png)

Let me know what you think on this (having mixed image reference type is not very elegant).

_Originally posted by @nosyn00b in https://github.com/UncleGoogle/galaxy-integration-humblebundle/issues/147#issuecomment-772896678_

**Comment by nosyn00b** [comment]
Also this should be closed referencing merge to the master of some days ago.

**Comment by UncleGoogle** [comment]
right, closing via #149
