### ISSUE TITLE
Plugin stays "offline" and doesn't show Subscriptions

### ISSUE THREAD

**Issue by Mrbazil** [UncleGoogle/galaxy-integration-humblebundle#151]
**Describe the bug**
After reinstalling the Plugin (to maybe fix the Humble Choices Bug - which didn't work) and even reinstalling gog galaxy the plugin stays offline in the "Integrations" tab of the gog galaxy settings. 
![image](https://user-images.githubusercontent.com/77669177/107569950-2e1aea80-6be9-11eb-979d-ab4118306def.png)

Clicking "Retry" starts the login procedure and maybe imports all non-subscription HB-Games, but doesn't fix the problem. It stay offline and the Humble Choice Games don't show up.

Unfortunately i cannot provide steps to reproduce the issue, as i only got here by reinstalling (deleting and downloading again) the Humble-plugin to fix the Humble Choice Bug.

**Expected behavior**
To stay "connected" in the Integrations-Tab and show the HB-Subscription Games (e.g. Humble Choice)

**Plugin installed**
directly from Galaxy / manually from your repository releases
I tried both.
Same result

**Provide logs**
[plugin-humble.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/5961421/plugin-humble.zip)

**Comment by UncleGoogle** [comment]
Hi, should be fixed now. Released.

Unfortunately, because of strange Galaxy bug you need to reconnect plugin to have subscriptions visible again. Otherwise Galaxy just ignores that feature and never asks for a new data from subscriptions.

**Comment by Mrbazil** [comment]
Thanks a lot.
The plugin works as intended now. :-)
