### ISSUE TITLE
Can't login anymore

### ISSUE THREAD

**Issue by Phlaxith** [UncleGoogle/galaxy-integration-humblebundle#154]
**Describe the bug**
Hi! You recently updated the version of the plugin, and in that way I would install and connect with the Galaxy integrations menu (when it worked like 2 days ago it was a manual installation cuz it won't show me the integration in Galaxy at this time)
I disconnected the integration, then reconnect with Galaxy integration, but when I log-in, then I got this :

![image](https://user-images.githubusercontent.com/32924025/107873863-ef6d8480-6eb5-11eb-809a-bdd054f0fe2d.png)

I deleted the integration completely to make Galaxy install fresh but it doesn't work either.

**Expected behavior**
I want the plugin working back. I have too many games to show :(

**Plugin installed**
directly from Galaxy

**Provide logs**
[logs.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/5977449/logs.zip)

**Comment by Phlaxith** [comment]
I forgot to add this :
I have Google Authenticator on my Humble account, so I tried without too and it doesn't work.

**Comment by damiendetch** [comment]
Hello Phlaxith,

I was about to write something here as well. I have the exact same issue on my end. I also have the 2-steps authenticator for HumbleBundle. It's been happening for a few days now. I have no idea where this comes from.

**Comment by UncleGoogle** [comment]
Hi, the issue is fixed already (#151) and released. @damiendetch had installed newest version of the plugin, which was not available to all people though Galaxy yet. 

But for now I can see that the newest version is also available automatically in Galaxy. Just restart it - plugin should be updated.

**Comment by Phlaxith** [comment]
Ok everything is UP now :D 
Thank you both of you and sorry, I should also have search for closed issues referring the same problem I had !
