### ISSUE TITLE
Game in Humble Account misidentified, adding wrong game to library

### ISSUE THREAD

**Issue by SirPrimalform** [UncleGoogle/galaxy-integration-humblebundle#156]
The game "Journey To The Center of the Earth" (2003, Frogwares) in my Humble account is showing up in Galaxy as "Journey To The Center of the Earth" (2015, InSayn). 

Obviously it's because they have the same name, but since there are many unrelated games over the past 40+ years of gaming that coincidentally share names there must be some way of resolving these sorts of conflicts, right? 

If I go to manually add a game in Galaxy it lists a lot of possible Journey to the Centre of the Earth games including the one I need, but I can only add that one in addition to the one added by the Humble integration, it doesn't seem to be possible to correct the misidentification.

**Comment by UncleGoogle** [comment]
Hey, this has to be resolved by GOG gamesdb stuff, create a report from GOG Galaxy menu.

**Comment by SirPrimalform** [comment]
> Hey, this has to be resolved by GOG gamesdb stuff, create a report from GOG Galaxy menu.

I did wonder about that, but since GOG's gamesdb does have an entry for the correct version I assumed it was the HB integration misidentifying the game when importing the library.

So when the HB plugin scrapes my HB account for the library, presumably it only gets the names of each game? How does the process go from there? The more info I have, the more specific a ticket I can submit to GOG.

The process I'm imagining is:
1. HB plugin scans HB library, gets a list of names
2. HB plugin looks those names up on GOG's DB, picks the first result it finds
3. Adds those games to Galaxy library

Is that about right in simple terms? Is the "looking up the names" part performed by Galaxy itself or the integration plugin?

**Comment by UncleGoogle** [comment]
> The process I'm imagining is:
> 
> 1. HB plugin scans HB library, gets a list of names
> 2. HB plugin looks those names up on GOG's DB, picks the first result it finds
> 3. Adds those games to Galaxy library

I like your vision, but the point 2 is different: Galaxy does not expose its db/ any API for game matching, it is doing game matching itself based on names returned by plugin.

> Is that about right in simple terms? Is the "looking up the names" part performed by Galaxy itself or the integration plugin?

Plugin provides pair of game id and game name, and that is all. What `id`? Plugin decides. From what people observed the output is not invariant, I mean, sometimes the first name that is provided by the plugin causes "unknown game" in Galaxy, or wrong/no images for given game etc. It is fixed after some time, probably by GOG stuff manually.

**Comment by SirPrimalform** [comment]
Gotcha, thanks. You say the plugin decides the id? Surely this means the plugin has some influence over how the game is identified?
Apologies if I'm misunderstanding. Anyway, I'll make a ticket with GOG, but I'm half expecting them to say it's the plugin developer's responsibility. 😛

**Comment by UncleGoogle** [comment]
The `id` is just a string the plugin return along with name. Then Galaxy uses this id to ask plugin for other things like size or installation state.

> plugin has some influence over how the game is identified?

not exactly. It is more like two options:
- matched automatically if the provided name matches with a game from IDGB
- not matched (then the name plugin provide is visible in Galaxy, no covers, etc.), but it can be corrected after some time.
- 
> I'm half expecting them to say it's the plugin developer's responsibility. 😛

I've never seen such response for gamesdb issue. Should be fixed by them. Or ignored...
