### ISSUE TITLE
Crashes on launch: MacOS 10.14.5, Galaxy 2.0.4

### ISSUE THREAD

**Issue by Taffer** [UncleGoogle/galaxy-integration-humblebundle#16]
**Describe the bug**
Installed the unzipped plugin, restarted Galaxy, went into Preferences -> Integrations, and clicked Connect. A red message in the "Connected/Not connected yet" field says "Plugin has crashed. Retry."

**Expected behavior**
Expected the plugin to work as well as it did on my Windows 10 system. The Connect button has switched to "Disconnect".

**Attach logs**
[plugin-humble-log.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3477121/plugin-humble-log.zip)

**Comment by UncleGoogle** [comment]
Thanks for report. I cant release patch right now, but you can probably fix it by replaceing one line in plugin.py to:

self._app_finder = None

Note that there is no support for lauchong games on macos (#13)

**Comment by UncleGoogle** [comment]
Should be fixed by #17

**Comment by Taffer** [comment]
Confirmed, works like a charm. Thanks! 👍
