### ISSUE TITLE
Can't see humble choice or trove games

### ISSUE THREAD

**Issue by Bertaz** [UncleGoogle/galaxy-integration-humblebundle#161]
**Describe the bug**
Today I noticed that the plugin stopped showing newer choice months from around June. I relogged in the integration hoping to solve it.
All my choice months and trove games disappeared, I now only have games from keys and drm-free.
I think it's caused by the absence of options in Settings->Features: 
![image](https://user-images.githubusercontent.com/44445647/135537790-6b7be8a5-9dc4-4f50-b9a0-08570e0afa29.png)
I reinstalled the plugin from galaxy, installed the latest release from here, nothing worked

**Expected behavior**
Show all the choice months and the trove

**Plugin installed**
directly from Galaxy AND manually from your repository releases

**Provide logs**
[HumblePluginLogs.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/7262866/HumblePluginLogs.zip)

**Comment by UncleGoogle** [comment]
Hello @Bertaz,

check this build please

[humblebundle_0.9.5a.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/7270579/humblebundle_0.9.5a.zip)

**Comment by Bertaz** [comment]
That build works.
It increased considerably the first import times, before it took less than a minute, now it takes a couple of minutes. Not a problem as it happens only after connecting for the first time.

The subscriptions option under Features reappeared and shows all the humble choices, the newest one for some reason is at the bottom with a star:
![image](https://user-images.githubusercontent.com/44445647/135716458-689306c2-9653-45a8-bc9e-e262cbaf61f0.png)
But it doesn't appear in the Subscriptions tab:
![image](https://user-images.githubusercontent.com/44445647/135716494-88bb7648-3a60-41ea-87be-add578285d9e.png)

Also, after a Galaxy restart, the option under Features disappeared as before, but the already loaded subscriptions remained
> […]the absence of options in Settings->Features: ![image](https://user-images.githubusercontent.com/44445647/135537790-6b7be8a5-9dc4-4f50-b9a0-08570e0afa29.png)


[humblePluginLog.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/7271472/humblePluginLog.zip)

**Comment by UncleGoogle** [comment]
Ah, ok, so there was a code leftover from what I've tried to achieve to address this issue: #159 locally on my machine.

I mean - I marked the latest subscription was marked with "*", but there was one more bug when Galaxy asks for this subscription games.
I'll do that later on - if you have any opinions about that - please let me know in corresponding issue.

For now, I'll release the fix for subscriptions.

**Comment by UncleGoogle** [comment]
Before release I need to also check with account that have never subscribed.

So in case it won't happen this week I'm posting beta build here:
[humblebundle_0.9.5b.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/7274352/humblebundle_0.9.5b.zip)

@Bertaz could you check once again? Reconnection needed.

**Comment by Bertaz** [comment]
> Before release I need to also check with account that have never subscribed.

I don't have a never subscribed account, but from #162 I'm guessing you already tested that
<br/>

> @Bertaz could you check once again? Reconnection needed.

Now everything works correctly, except that after a Galaxy restart the option under Features disappears, but the already loaded subscriptions remain:
> […]absence of options in Settings->Features: ![image](https://user-images.githubusercontent.com/44445647/135537790-6b7be8a5-9dc4-4f50-b9a0-08570e0afa29.png)
<br/>

[humblePluginLog_5.10.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/7287583/humblePluginLog_5.10.zip)

**Comment by UncleGoogle** [comment]
Hey, thanks for the test.

In plugin logs everything looks good, except that after restart Galaxy just do not ask for subscriptions :(

I think it may be related to https://github.com/gogcom/galaxy-integrations-python-api/issues/180 as also `get_owned_games` is not called.
