### ISSUE TITLE
Importing subscriptions fails with code 4 (Backend responded in unknown way)

### ISSUE THREAD

**Issue by mmoderau** [UncleGoogle/galaxy-integration-humblebundle#165]
Importing subscriptions fails.

Plugin installed directly from Galaxy.
1. After connecting the plugin, synchronization with Galaxy seems to hang (which is more of a Galaxy problem).
1. After restarting Galaxy, the `import_subscriptions` task fails with following log message:
```
2021-11-05 12:24:07,447 - webservice - DEBUG - GET, https://www.humblebundle.com/subscription, (), {'allow_redirects': False}
2021-11-05 12:24:07,702 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "268", "error": {"code": 4, "message": "Backend responded in unknown way", "data": "cannot parse webpack data"}}
```
Human readable response:
```JSON
{
    "jsonrpc": "2.0",
    "id": "268",
    "error": {
        "code": 4,
        "message": "Backend responded in unknown way",
        "data": "cannot parse webpack data"
    }
}
```
The URL that plugin tried to reach (`https://www.humblebundle.com/subscription`) returns code 302 and redirects to `https://www.humblebundle.com/subscription/home`.

### Logs
[logs.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/7485795/logs.zip)

**Comment by UncleGoogle** [comment]
@mmoderau  could you test this build? Worked before refactor, but now I have no subscription to verify that.
[humblebundle_0.10_0a.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/7919142/humblebundle_0.10_0a.zip)

**Comment by mmoderau** [comment]
I'll try to do that on Monday.
