### ISSUE TITLE
Support Humble Games Launcher installs!

### ISSUE THREAD

**Issue by 27hectormanuel** [UncleGoogle/galaxy-integration-humblebundle#169]
![image](https://user-images.githubusercontent.com/22853711/155611824-3c491446-259c-4e16-84f7-7cb24743176b.png)
Support the beta launcher subscription games

**Comment by UncleGoogle** [comment]
research done:
- there is nice URI protocol to install/launch games `humble://<cmd>/<machine_name>`
- I've installed one game (Forager) from "By Humble Games" and looks it has no DRM so I can skip Humble Launcher this way and run it directly (may be important for #170)
- there is one big config file at `%appdata%/Humble App/config.json` to read all games with states and even download progress (if Galaxy ever supports it)
    - there is even `lastPlayed` timestamp so "Played Recently" in Galaxy for games run by launcher will be visible
    - "user"/"user_key" - app oauth client token?

**Comment by UncleGoogle** [comment]
Now released in 0.11.0!

Please share your feadback if it works for you.

**Comment by UncleGoogle** [comment]
Note on last_time usage: looks like Galaxy ignores "last played" timestamp returned to game keys corresponding to subscription game. What a pity.

@27hectormanuel let me know if you would like to see native support for launching games from humble app -- for now most of them seems to be drm-free, so it would possible to for example attach double-click on Play button to launch directly (and having it visible in "Recently Played" probably)
