### ISSUE TITLE
Add subscription support for the Humble Games Collection

### ISSUE THREAD

**Issue by BlacRyu** [UncleGoogle/galaxy-integration-humblebundle#170]
The [Humble Games Collection](https://www.humblebundle.com/membership/collection) is a new Humble Choice perk which should be supported as a subscription in GOG Galaxy. This new collection is similar to the Humble Trove in that it is a growing collection of games available to active Humble Choice subscribers, but differs in that it includes full games with DRM in the form of the new Humble App launcher (which should ideally receive support as well: #169).

![image](https://user-images.githubusercontent.com/10762433/155864488-fb7f8717-f83e-4a1f-97d2-193029c4566e.png)

**Comment by UncleGoogle** [comment]
@BlacRyu thanks for the details and splitting the feature request upfront. :+1: I'm interested in providing full support at some point though (as always) I don't have much time to do it.

Firstly I need to finish with #165 #167 (need testers!) and then #164 (as the legacy orders endpoint may be sunset at some point)

At this stage technical researches and dirty POCs are appreciated to showcase the requirements.
Current modules may be too tightly coupled; I'm open to architectural refactor proposals.

**Comment by 27hectormanuel** [comment]
Looking forward to the addition of launcher support soon. In the meantime I should be adding games manually.
