### ISSUE TITLE
humble_v0.11.0_win.zip flagged for Trojan.Cometer.cmb by Jiangmin scanner at VirusTotal

### ISSUE THREAD

**Issue by mwarrenus** [UncleGoogle/galaxy-integration-humblebundle#188]
**Describe the bug**
[VirusTotal's run of the Jiangmin scanner flagged humble_v0.11.0_win.zip](https://www.virustotal.com/gui/file/db93fd8e2853be28f5900fc02693e9a7c883ea45ead228200af8118de1edba11) as containing [Trojan.Cometer.cmb](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Trojan:Win32/Cometer!MSR&ThreatID=2147761129). 

**Expected behavior**
Downloadable releases of the Humble Bundle plugin for GOG Galaxy should have a clean VirusTotal scan prior to posting.

**Plugin installed**
Manually from the [releases page of the UncleGoogle/galaxy-integration-humblebundle repository](https://github.com/UncleGoogle/galaxy-integration-humblebundle/releases)

**Provide logs**
Please see the [VirusTotal scan report for humble_v0.11.0_win.zip](https://www.virustotal.com/gui/file/db93fd8e2853be28f5900fc02693e9a7c883ea45ead228200af8118de1edba11).

Edit: Perhaps the [VirusTotal GitHub Action](https://github.com/marketplace/actions/virustotal-github-action) could be used to automate this check.

**Comment by UncleGoogle** [comment]
@mwarrenus thanks for the report!

I see 2 possibilities:
1. false positive
2. one of dependencies contains encrypted trojan (yes, I didn't lock dependencies so it was possible that malicious actor updated one of dependency of direct dependencies) 

I'm marking this release as potentially dangerous to discourage from downloading.

-------

Please help me with finding the culprit file -> if you have such option in VirusTotal (isolated sanbox ect.).

**Comment by UncleGoogle** [comment]
@SilmorSenedlen and @SparrowBrain -- making you, as you already reacted with emoji to that release. My recommendation is to remove / downgrade. 

@mwarrenus did you ever used older plugin releases w/o antivirus complains?

**Comment by SparrowBrain** [comment]
Thank you so much for the heads up! Gonna remove for now. Overall really like the plugin, thanks for all the work!

**Comment by Theblockbuster1** [comment]
I suspect that it may just be a false positive as only one antivirus has detected malware.

**Comment by SilmorSenedlen** [comment]
> My recommendation is to remove / downgrade.

Thx for info.

**Comment by SparrowBrain** [comment]
ESET scan didn't detect any issues

**Comment by Dr-Flay** [comment]
You can guarantee it is a false positive.
When a Chinese AV that is designed to think everything is a threat, but none of the trustable AV see a threat, you can have faith it is fine.
If Bitdefender, Avira, Kaspersky, eset and MalwareBytes detected something then it is worth worrying.

**Comment by Ozzuneoj** [comment]
> @SilmorSenedlen and @SparrowBrain -- making you, as you already reacted with emoji to that release. My recommendation is to remove / downgrade.
> 
> @mwarrenus did you ever used older plugin releases w/o antivirus complains?

Just curious... is there any update to the status of this? Should 11.0 still be avoided? Thank you.

**Comment by Theblockbuster1** [comment]
@Ozzuneoj In my opinion it should be completely safe, I'm using it and I seem to be doing fine. It's up to you of course, but I'm quite certain that it's just a false positive. If 59 out of 60 antiviruses say that it's safe, I'm not going to listen to the 1 that says otherwise, especially if it's just from some company which I've never heard of.

**Comment by Bertaz** [comment]
This is a false positive. The modified files between 0.10.1 and 0.11.0 are only those: 
![image](https://user-images.githubusercontent.com/44445647/180182526-c3685508-040c-4dde-bd5f-f2ec58e3aedb.png)
3 text files with no malicious edits and 1 binary file `normalizer.exe`.
The binary file has full clear on VT for both version [10.1](https://www.virustotal.com/gui/file/2ee787147a6c371eff32c4fb5248636e1458b1496ca629634c115809239ffdda) and [11.0](https://www.virustotal.com/gui/file/d3e85dd8647e6182a603b64ce6e31fa9832cefa38e10ce8e13c3e1e77d5093dc). This includes also Jiangmin.

Imo the solutions are only two:
1. Report the false positive on the zip file to Jiangmin (looking online the procedure appears to be send an email with the file to support[at]jiangmin[dot]com[<sup>[1]</sup>](https://groups.google.com/g/virustotal/c/iRq5Ojn4W8k/m/zjWomLWPCAAJ)). Keep doing this for every obscure AV that flags a false positive in the future.
2. Close the issues explaining that detection on less than 10% of virusotal vendors with no big AV name (Kaspersky, Microsoft, ecc) is 100% a false positive.

The disclaimer on [release 0.11.0](../releases/tag/v0.11.0) should be removed. @UncleGoogle

**Comment by UncleGoogle** [comment]
Ok, closing then, thanks for all your reviews!

I'll also lock dependencies and update in separate releases or commimts, so in the future similar cases will be easier to check.
