### ISSUE TITLE
Duplicated games

### ISSUE THREAD

**Issue by Lahiri** [UncleGoogle/galaxy-integration-humblebundle#19]
**Describe the bug**
Some games are shown in 3 copies. One is for the trove (this is another issue), but the other 2 should be merged.

I identified the issue for the following games:
- Avadon The Black Fortress
- Limbo

In addition to this, I have a few "Unknown game" entries.

**Expected behavior**
The duplicates should be merged into one entry.

**Screenshots**
![image](https://user-images.githubusercontent.com/1379165/63264144-9e61dd80-c28a-11e9-9e19-5bd698879a41.png)

![image](https://user-images.githubusercontent.com/1379165/63264215-d701b700-c28a-11e9-885c-785bbf2c078a.png)

**Attach logs**
[plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3515777/plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log.zip)

**Comment by owlnical** [comment]
I have the same problem. Limbo, Super Meat Boy. There are also a lot of duplicates, but those might be soundtracks right?

**Comment by UncleGoogle** [comment]
Thanks for comments and logs. I've used it while working on 0.4 so in this moment I do not send 2 games with the same title, and the priority order is set in config.ini file in plugin directory.

There is also support for 3rd party keys (steam, origin, uplay, battlenet) and those games _may be_ shown as a duplicated game, or may not, if the title was different.

For example if you have games with title (human_name) like following:

- Limbo (a bundle1 - direct download, id: limbo)
- Limbo (direct_buy, id: limbo_storefront)
- Limbo (trove, id: limbo_trove)
- Limbo Key (a bundle1 - steam key, id: limbo_steam)

In galaxy there should be shown 2 limbo games that have different title (shown on mouse over):
- Limbo
- Limbo Key

Firstly I've tired to normalize the id (machine_name), but humble API responses have no strict convention. So for same games it works (like Limbo), but for other, their id are completely different. So for now you can distinguish those duplicated games by title. It is the best what I can do.

**Comment by UncleGoogle** [comment]
As far as "unknown game" are concerned, please prepare bug report for Galaxy. I you want to help more you can find which exactly games are those unknown titles. Just see the log file for humble bundle and heck what games are send as "owned_games" (the long list with licenses).
Then check which of those game are not shown

**Comment by UncleGoogle** [comment]
As far as "unknown game" are concerned, please prepare bug report for Galaxy. I you want to help more you can find which exactly games are those unknown titles. Just see the log file for humble bundle and check what games are send as "owned_games" but not shown in Galaxy
