### ISSUE TITLE
source icon in games list is missing

### ISSUE THREAD

**Issue by RelativeProgramming** [UncleGoogle/galaxy-integration-humblebundle#2]
![image](https://user-images.githubusercontent.com/16016861/61540894-db924000-aa3e-11e9-927c-906ea151cb72.png)
![image](https://user-images.githubusercontent.com/16016861/61540901-e220b780-aa3e-11e9-94d5-d98c6032e193.png)

I could make such an icon. I just need to know how large and in which format it should be.

**Comment by RelativeProgramming** [comment]
It seems to be not possible at the moment, to add such a icon to a plugin.
I've created an issue in the official repository:
https://github.com/gogcom/galaxy-integrations-python-api/issues/26

**Comment by EccTM** [comment]
the [battlenet community integration](https://github.com/FriendsOfGalaxy/galaxy-integration-battlenet) has a source icon implemented though, unless that platform's icon was already baked into galaxy?

**Comment by UncleGoogle** [comment]
HB Icon present from Galaxy Atlas update. Closing
