### ISSUE TITLE
Some games not recognized ("Unknown game")

### ISSUE THREAD

**Issue by MarkoH01** [UncleGoogle/galaxy-integration-humblebundle#28]
**Describe the bug**
The following games were not recognized and listed as "Unknown game" without any option to add them manually.

Dungeons of Dredmor
Far Sky
FRACT OSC
Osmos
Zen Bound 2

[logs.ZIP](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3612880/logs.ZIP)

**Comment by Iglum** [comment]
How did you find out what games that are "Unknown game"  apparently i had **462** games imported from humble and around of **60** of them shows as unknown games.

**Comment by UncleGoogle** [comment]
**"Unknown game"** is a Galaxy bug. Please send report to Galaxy instead (options icon - report issue).

Integrations do not deal with games metadata - they are matched on Galaxy backend. The only thing integrations send to the app is a list of game id's with titles.

@Igum to find the list of unknown games you can 
- refer to plugin log file:
    - (Windows) %programdata%\GOG.com\Galaxy\logs
    - (macOS)  /Users/Shared/GOG.com/Galaxy/Logs
- search for sent "owned_games". 
- compare the list with what you see in Galaxy. I think it may be helpful for them to fix game titles as their database may be manually curated.

In general, Galaxy should use the title provided by an integration even if the game matadata (like covers) is not prepared on their backend. So the "unknown game" is undesireable feature (== bug).

**Game not shown at all** - sometimes games are not shown at all even if are send via integration (see log file). This happens with all products that can be classified as "not-games". For example game's audio (if not filtered out by #18) or DLCs. They are hide in Galaxy backend after some time, like someone do it manually every time the new game title/id is coming. 
- if you think it was a mistake - report to Galaxy

**Wrong game's metadata** - the same as above.

**Comment by MarkoH01** [comment]
I reported my non recognized games to the Galaxy team and they fixed it :)
