### ISSUE TITLE
Recognizing local state of game

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [UncleGoogle/galaxy-integration-humblebundle#34]
Hey,

I've came up on an issue in the integration which leads to it not properly recognizing the installation status of a game sometimes.

Installed Annas Quest -> integration correctly recognized it was installed
Uninstalled Annas Quest -> integration correctly recognized it was uninstalled
Installed Deponia -> integration doesn't recognize it was installed

I think it might be related to the windows registry logic keeping track of the number of keys. It gets detected correctly after restarting galaxy.

![image](https://user-images.githubusercontent.com/48480506/66568571-02f23800-eb6a-11e9-893c-3c450625817c.png)

[plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3712545/plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log)

**Comment by UncleGoogle** [comment]
Hi, thanks for report.
Could you please show ful paths of registry keys for both games?

**Comment by FriendsOfGalaxy** [comment]
Anna 

Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Anna's Quest_is1

Deponia

Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{F7D0BCAC-62CD-4133-A119-993410C88BA6}_is1
