### ISSUE TITLE
Can't install 2 games (Fototonica & Indiana Jones® and the Fate of Atlantis™)

### ISSUE THREAD

**Issue by Riku55** [UncleGoogle/galaxy-integration-humblebundle#38]
1) Fototonica
When clicking on install, nothing happens. In log, there's an error when trying to install the game. I'll add the log files, I'll paste the error that I found in the log anyway:
File "C:\Users\Rik55\AppData\Local\GOG.com\Galaxy\plugins\installed\humblebundle_0.5.0-alpha3\plugin.py", line 149, in install_game
    chosen_download = self._download_resolver(game)
  File "C:\Users\Rik55\AppData\Local\GOG.com\Galaxy\plugins\installed\humblebundle_0.5.0-alpha3\humbledownloader.py", line 20, in __call__
    return self._find_best_subproduct_download(game)
  File "C:\Users\Rik55\AppData\Local\GOG.com\Galaxy\plugins\installed\humblebundle_0.5.0-alpha3\humbledownloader.py", line 41, in _find_best_subproduct_download
    raise NotImplementedError(f'Found downloads: {len(download_items)}. All: {system_downloads}')
NotImplementedError: Found downloads: 0. All: [<model.download.SubproductDownload object at 0x00B44AD0>]

2) Indiana Jones® and the Fate of Atlantis™
Install option is grayed out. Downloading installer on humble bundle homepage works fine.

[logs.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3753447/logs.zip)

**Comment by UncleGoogle** [comment]
1. Looks like in download "name" is neither "Download" nor "32-bit" - I'm not very surprised, as humblebundle reset api response is not very standarized... 

Could you paste your json response for https://www.humblebundle.com/home/library for this game?
I need "subproducts" key - will try to fix.

Margin note: I'm not proud of current state of download resolver. It would be better to create GUI with list of all downloads to be choose by user. In v1.0 for sure.

2. Hmm, and is there any tooltip over grayed-out button?

**Comment by Riku55** [comment]
[androidbundle13.txt](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3758907/androidbundle13.txt)

1. Not sure what exactly you need, so Just copied the whole bundle out of it and removed the redeemed keys. Platform is Win10 in case that makes any difference.

2. Tooltip says "Not compatible". The installer is an exe file, so that shouldn't be a problem on Windows.

**Comment by UncleGoogle** [comment]
1. Funny, the download name for Fotonica on windows is ".zip". I'll fix this soon.

2. I see... I think this will be fixed in #35 where we can tell Galaxy that this game is released on specific OS (Galaxy currently uses its own source of information so far).

**Comment by UncleGoogle** [comment]
@Riku55 can you retest downloading fotonica using https://github.com/UncleGoogle/galaxy-integration-humblebundle/releases/tag/v0.5.0-beta ?

**Comment by Riku55** [comment]
Now I get HTTP Error 403 for every download page.
Download link example (in this case for Fototonica):
https://dl.humble.com/FOTONICA_WIN.zip?gamekey=bYuNFDrMEbYeEDmM&ttl=1571769110&t=dea5d592c579ea41028f4233855c5357

Log looks clean for me.
[plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.txt](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3780968/plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.txt)

config file is the same I used before (drm-free and trove active, one 'installed' path which exists but is empty).

**Comment by UncleGoogle** [comment]
Hmm, looks like you lost authentication in plugin.
What is happen on reconnect?

**Comment by Riku55** [comment]
Don't know why it lost authentication before, but reconnect and it works fine now, aswell for Fototonica :)

**Comment by UncleGoogle** [comment]
Ok, thanks for testing. I'm closing this as fixed. We will probably see this auth lost in the future if it is real problem.
