### ISSUE TITLE
FOG Fork Autoupdate Request

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [UncleGoogle/galaxy-integration-humblebundle#40]
Hey, 

we're planning on creating a fork/autoupdate system with selected plugins. This would allow us to create a list of curated and reviewed plugins which could be of use to GOG Galaxy people.

Of course you will be credited as the creator and developer of the plugin in the fork readme and possibly other places.

Before we do that we need to ask you to create a `fog_release` branch which would contain only your plugin code, `manifest.json` and a `requirements.txt` file (without `modules` directory). For Github releases, we will include whole directory where `manifest.json` is placed and build dependencies directly there. This is for easier code verification. Also, please use only not extended symver versions in `manifest.json`. That is because we need to compare versions to know if synchonization is needed.

Code for repo synchronization can be found here: https://github.com/FriendsOfGalaxy/galaxy-integrations-updater

**Comment by UncleGoogle** [comment]
Is it OK now? 
I didn't create `fog_release` branch because not so many changes were needed and I see in updater code there is fallback check for `master` branch if `fog_release` doesn't exists.

**Comment by FriendsOfGalaxy** [comment]
Yes, almost. Please do not use extended sematic versioning (only simple x.y.z) because version comparing is violated.

**Comment by FriendsOfGalaxy** [comment]
Works ok, now, thanks!
