### ISSUE TITLE
Login doesn't work on versions after 0.41

### ISSUE THREAD

**Issue by user00101010** [UncleGoogle/galaxy-integration-humblebundle#44]
**Describe the bug**
1. Install Humble Bundle plug-in version 0.5.0 beta from the official repo or GalaxyFriends repo.
2. Launch GOG Galaxy 2.0 and click Connect on the Humble Bundle integration
3. Login with your details
4. Returns to Settings screen with "Connecting message"
5. After about a minute, the connection times out and an error message "Connection Lost" is displayed

**Expected behavior**
5. Display "Connected" message and start importing library

*NOTE:* Can confirm that the expected behavior is happening on version 0.4.1 after about a second.

**Attach logs**
[plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3794201/plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log)

**Comment by mbanczerowski** [comment]
`PermissionError: [Errno 13] Permission denied: 'C:\\Program Files (x86)\\GOG Galaxy\\plugins\\Humble Bundle\\config.ini'`
I don't know how you run this, but looks like you put `Humble Bundle` folder in `plugins` but should be `plugins\\installed`. Could you recheck 0.5?

**Comment by UncleGoogle** [comment]
@user00101010, I cannot reproduce your bug. However, as have been mentioned, log traceback suggests that plugin is in wrong directory (in C:\\Program Files (x86)\\GOG Galaxy\\plugins instead of 'C:\\Program Files (x86)\\GOG Galaxy\\plugins\\installed ). Could you please double check this issue?

**Comment by user00101010** [comment]
Correct, I install all my add-ons in "C:\Program Files (x86)\GOG Galaxy\plugins" and never had issues up until now. Moving it to "C:\Program Files (x86)\GOG Galaxy\plugins\installed" didn't work as the client stopped detecting the client as installed (although interestingly, my current library remained available, does GOG Galaxy make a cache of the synced games?)

However moving the add-on to "%localappdata%\GOG.com\Galaxy\plugins\installed" did resolve the issue. Version 0.5.0 was detected in the client and I was able to log-in!

**Comment by UncleGoogle** [comment]
Ah, now I see what was wrong.
Galaxy in `C:\Program Files (x86)\GOG Galaxy\plugins` keeps official integrations
and looks for community integrations in `%localappdata%\GOG.com\Galaxy\plugins\installed`
(my previous comment was wrong, as there is no such thing for Galaxy as `C:\Program Files (x86)\GOG Galaxy\plugins\installed`
My plugin has failed while reading config file in location where it cannot have read permission (Program Files (x86)). It's better to move all manually added integrations to %localappdata%
