### ISSUE TITLE
Connection Lost if I close GOG Galaxy

### ISSUE THREAD

**Issue by jackcaos1** [UncleGoogle/galaxy-integration-humblebundle#48]
everytime I close GOG Galaxy and reopen it ( as when I am starting the PC) I have to reestablish the Connection to Humble bundle

**Comment by UncleGoogle** [comment]
It shouldn't happen. Can you send your log files? Log location is given when you create new issue-bug report

**Comment by jackcaos1** [comment]
[plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3821547/plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log)

Somehow i created this issue without the template ...

**Comment by UncleGoogle** [comment]
I apologize for late response. I'm not sure if this is the real problem, but there is parse error in logs:
```TomlDecodeError('Reserved escape sequence used (line 30 column 1 char 1620)')``` 

and sometimes in char 1612. Probably you should try with two backslashes `\\` in all paths instead of one `\`. You can also use `/` I suppose. Definitely I need to add some tests for parsing config...

**Comment by 13xforever** [comment]
this happens if you have _any_ issues with config.ini (e.g. if you specify a non-existent path, which is normal and can happen for a number of reasons)

on restart it will error out and  will reset everything, including connection and config.ini (probably as part of the new connection setup)

**Comment by UncleGoogle** [comment]
@13xforever Theoretically loading settings and connections are separated. And parsing local config should fallback to defaults. 

But in your example 2 (read-only file) this is indeed a problem. Was it read-only by default or there is a usecase to make it RO?

**Comment by 13xforever** [comment]
it was resetting config.ini when it was failing the directory check, importing keys, which I do not want, so I made it read only trying to force the config I want

**Comment by UncleGoogle** [comment]
@13xforever @jackcaos1,
Strict syntax of config should no longer be a problem as new graphical interface is introduced #83 
Release 0.7.0 should be available via Galaxy soon.
