### ISSUE TITLE
Latest Trove games aren't added to Galaxy

### ISSUE THREAD

**Issue by Diskutant** [UncleGoogle/galaxy-integration-humblebundle#49]
**Describe the bug**
Yesterday 3 new games were added to the Trove, but they aren't added to GoG Galaxy using this integration. The games are The Whispered World Special Edition, RuneStone Keeper and Operator.

Operator was already available as a regular Monthly games last week and is already handled by #37 I think. 

**Expected behavior**
RuneStone Keeper and The Whispered World Special Edition should be added to Galaxy.

**Attach logs**
[logs.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3827063/logs.zip)

**Comment by UncleGoogle** [comment]
Thanks for report. You find a serious bug. Check this if it works for you:
[humblebundle-refresh-fix.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3828788/humblebundle-refresh-fix.zip)

**Comment by Diskutant** [comment]
I tried that version now, but those games still don't show up for me.

**Comment by UncleGoogle** [comment]
Oh, my bad, I've zip wrong folder. Try this:
[humblebundle-fix-refresh.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3833041/humblebundle-fix-refresh.zip)
(and make sure you restart Galaxy)

**Comment by Diskutant** [comment]
Still no luck
[logs.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3833373/logs.zip)

**Comment by UncleGoogle** [comment]
thanks. Can you upload only the log file without numeric extension? It is the latest one.

**Comment by Diskutant** [comment]
It's in the latest .zip file, but anyway here it is again:

[plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log.txt](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3833469/plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log.txt)

**Comment by UncleGoogle** [comment]
> It's in the latest .zip file

only 1-10 logs are there. https://i.gyazo.com/461200ec50326739b561078b74c8e39e.png The newest log is from 11.11 9:20 so before iteresting section

> but anyway here it is again
plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log.txt

and the oldest log from above is from 11.11 23:03 so after all interesting things.

Sorry for pinning you so much it is a bit annoying I know, but Galaxy is rolling logs, that means if it get about 5MB then all logs are renamed, log.txt -> log.1; log1 -> log2 ect. and new one is created. And both missing games are now shown for me in Galaxy, so we need to know that is wrong in your plugin.

To be 100% sure we talk about the same, please follow those steps:
- make sure "troves" are in config file 
- new plugin version is the only one version of humblebundle plugin in `installed` folder.
- restarting Galaxy or click "Sync Integrations"
- wait 2 minutes
- if still no success, please zip and attach 2 log files:
    - `plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log.txt`
    - `plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log.1`

**Comment by Diskutant** [comment]
> only 1-10 logs are there

oh, sorry must have missed that one file while zipping.

> Sorry for pinning you so much it is a bit annoying I know

No it's not annoying, it's all good. I'm happy to get responds on my reports and stuff.

> To be 100% sure we talk about the same, please follow those steps:

 I did all those steps yesterday without any luck, but I left the PC (and GoG Galaxy) running since yesterday, and now I come back to it, and those 2 games are there!

So I guess we can close this now. 
Thank you very much! :)
