### ISSUE TITLE
Plugin has crashed

### ISSUE THREAD

**Issue by dstumme** [UncleGoogle/galaxy-integration-humblebundle#5]
**Describe the bug**
When trying to connect to HumbleBundle from Galaxy 2.0's Settings page, I get "Plugin has crashed" and a retry link.  Retrying does not resolve the issue.

**Expected behavior**
Login prompt of some kind to connect Galaxy to my Humble account.

**Screenshots**
![hb galaxy](https://user-images.githubusercontent.com/53378704/61997762-a310e880-b074-11e9-87aa-f8da4a622203.jpg)

**Attach logs**
[plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3438440/plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.zip)

**Comment by Darkenend** [comment]
Exactly the same thing is happening to me.

**Comment by UncleGoogle** [comment]
Hi guys, thanks for report, 0.2.2 will fix this.

**Comment by dstumme** [comment]
Doesn't crash any more.  Doesn't load a games list either.  Closing this, and new issue submitted for the library problem.
