### ISSUE TITLE
Info about two step authentication

### ISSUE THREAD

**Issue by vinodmishra** [UncleGoogle/galaxy-integration-humblebundle#52]
I had never switched away from Authy to TOTP for humble bundle so when I was trying to install this plugin and connect it I got no errors but none of my games were showing up.  I just discovered that this was the issue by accident.  Maybe the readme could use a note about that if there are other people facing this issue.

**Comment by UncleGoogle** [comment]
Hi, can you elaborate more? What is TOTP? Authy is sort of legacy humble authenticator, right?
I'm using Google Authenticator with no issues, it should be no problem for Authy i think.

**Comment by vinodmishra** [comment]
TOTP (https://en.wikipedia.org/wiki/Time-based_One-time_Password_algorithm) is the 2FA standard that Google Authenticator uses and so do a lot of other authenticators like Authy. However, initially Humble Bundle had gone with Authy's own implementation which was not TOTP. Later on humble bundle decided to actually use TOTP so people could use any authenticator they like instead of just Authy (https://www.reddit.com/r/humblebundles/comments/agsza5/humble_bundle_switching_from_authy_to_google/)

My games list was always empty until I switched to the new method. I am not sure where the logs are unfortunately.

**Comment by UncleGoogle** [comment]
Thanks for explanation. 2FA mechanizm should not impact on authentication result (the simple_auth cookie) that the plugin uses.

Logs location and descr. is in [bug report template.](https://github.com/UncleGoogle/galaxy-integration-humblebundle/issues/new?assignees=&labels=bug&template=bug_report.md&title=)

**Comment by vinodmishra** [comment]
Unfortunately nothing great in the logs as such. It could be that it's just a coincidence that the plugin just started working the same time as I switched my authentication method so closing this.
