### ISSUE TITLE
Fetching owned games fails if "trove" is in the sources list

### ISSUE THREAD

**Issue by EmberQuill** [UncleGoogle/galaxy-integration-humblebundle#57]
**Describe the bug**
Importing owned games fails when "trove" is one of the sources in config.ini. Based on the logs, as far as I can see, it looks like the error is thrown from `had_trove_subscription`. Removing Trove from the sources and restarting GOG allowed all my other Humble games to import. Re-adding Trove caused the error to show up in the logs again, but my previously-imported games were still there.

**Expected behavior**
Trove games are successfully imported, or if the import fails, it does not block the other sources from importing.

**Provide logs**
[plugin-humble.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3872334/plugin-humble.zip)

**Comment by UncleGoogle** [comment]
Thanks! Fixed. Will be released in 5.3 in this week probably
