### ISSUE TITLE
Plugin - pluginID/humble is not responding.

### ISSUE THREAD

**Issue by Verayth** [UncleGoogle/galaxy-integration-humblebundle#67]
**Describe the bug**
https://mantis2.gog.com/view.php?id=22442
This appears to be similar to issue #5 , which was fixed in 0.2.2.  I get a login prompt and then an account verification screen.  After entering all those, the plugin times out after about 20 seconds and then crashes.  From the log, the crash appears to be "unhandled ErrorReason 'AbortedByUser'" after a "request to stop plugin" by the client.

**Expected behavior**
have plugin login to humble without plugin timing out and crashing.

**Plugin installed**
directly from Galaxy

**Provide logs**
Hare are entries from all the various logs at around the time of the error:
[ErrorLogs-plugin-humble-20191203_1253.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3918030/ErrorLogs-plugin-humble-20191203_1253.zip)

**Comment by UncleGoogle** [comment]
Hi, thanks for report. Looks like plugin hang on just after authorisation. Is it happening all the time?
Can you attach whole galaxyclient.log after a crash? Maybe we will find more info there...
And have you changed config?

**Comment by Verayth** [comment]
I've tried 9 times since 11/23, and it's timed out every time.  Here is the log, which includes a couple of tries and ends whenever the log rolled over about 7 hours later.  I have not touched the config file.

[GalaxyClient.log.3.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3924485/GalaxyClient.log.3.zip)

**Comment by UncleGoogle** [comment]
Sorry for late response, I was busy. Honestly I have no idea what is happening. I've added more logs to the build and updated galaxy API. Please check with this.

[humblebundle_0.5.4b.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3946353/humblebundle_0.5.4b.zip)

**Comment by Verayth** [comment]
OK, I deleted the contents of the plugin folder, unpacked this version into it, and was able to connect and sync my games just fine.  I thought that odd, so I disconnected the plugin and had GoG re-download the plugin and was able to connect and sync with that version just fine also.  So really, no idea why I was having an issue in the first place.

**Comment by UncleGoogle** [comment]
Ok, thats weird indeed. Maybe parsing registry has deadlock and after restarting system i got unstuck?. Im closing now but If someone has the same issue - please use the zip from my previous comment and share logs.
