### ISSUE TITLE
doesnt read any games on my account at all anymore

### ISSUE THREAD

**Issue by derailedition** [UncleGoogle/galaxy-integration-humblebundle#69]
this is on the latest 2.0.11 version of galaxy. connecting turns up 'no results' for my account. it seems to connect as normal. one thing, it launches the CMD window and doesnt do anything with it.

**Comment by UncleGoogle** [comment]
Hey, thanks for report. Unfortunately it works fine on my machine.

I need more info from you about this bug. Please use this version of the plugin (more logging and updated Galaxy API):
[humblebundle_0.5.4b.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3946360/humblebundle_0.5.4b.zip)
and send me logs please.

Installation is described in readme. Logs location in the issue template: https://github.com/UncleGoogle/galaxy-integration-humblebundle/issues/new?assignees=&labels=bug&template=bug_report.md&title=

**Comment by trangalho** [comment]
As I'm experiencing the same issue, I went ahead and got a log of the issue occurring on my computer:
[plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3953251/plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.zip)

Hope that it's useful to you.

**Comment by derailedition** [comment]
I got it to work again here. did a redownload. deleted the integration data in all the plugins folders, both in appdata and in programdata.

**Comment by trangalho** [comment]
After you posted how you solved this, I tried that with no luck, so I ended up uninstalling Galaxy, deleting the content of the Appdata and ProgramData folders, reinstalled Galaxy and the only plugin that I installed was the version of Humble Bundle's plugin posted by UncleGoogle but the issue persists.

New log: 
[plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3955379/plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.zip)

**Comment by UncleGoogle** [comment]
@trangalho your logs tell me that plugin works perfectly fine. Games are reported to Galaxy properly.

**Comment by trangalho** [comment]
Looking in the storage\plugins folder, there is also a DB file with the content of my HB account's library, but on Galaxy it just shows up as "No results". I can't see what could be causing this, so I'll just leave it for another time.
Thanks for taking your time to take a look into it.

**Comment by UncleGoogle** [comment]
I would report to Galaxy - looks like a bug in a user database on their backend or maybe frontend "forgot" to display things? Maybe it is related to #65

**Comment by trangalho** [comment]
This issue was solved by updating to the latest Galaxy 2.0.12 beta.

**Comment by UncleGoogle** [comment]
Thanks for info, Im closing
