### ISSUE TITLE
No Humble games show up in Galaxy

### ISSUE THREAD

**Issue by fuzaco** [UncleGoogle/galaxy-integration-humblebundle#75]
**Describe the bug**
After installing the plugin, none of my games got imported. The "Humble Bundle" tab in Galaxy shows no results.

**Expected behavior**
It should've imported all my games. My config: 

[library]
sources = [ "drm-free", "keys", "trove",]
show_revealed_keys = false

[installed]
search_dirs = []

**Plugin installed**
Tried installing directly from the client and the rep as well. Neither made a difference.

**Provide logs**
Tried integration sync, disconnecting/reconnecting my account, but to no avail.

[plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3999268/plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.zip)

**Comment by UncleGoogle** [comment]
Hey, logs are ok. Please GalaxyClient.log if it is not the same issue like #65

**Comment by fuzaco** [comment]
Hey, thanks for the help. Here are the Galaxy Client logs.

I also noticed that there are now 7 additional Humble plugin logs that weren't there yesterday. Should I upload those as well?
[Galaxy.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/4000887/Galaxy.zip)

**Comment by UncleGoogle** [comment]
Yes, this is the same issue as #65. I'll close this, and workaraound original issue soon. Thanks for raising this once again.
