### ISSUE TITLE
wrong castle story recognised in games database

### ISSUE THREAD

**Issue by derailedition** [UncleGoogle/galaxy-integration-humblebundle#81]
this game https://www.igdb.com/games/castle-story
is recognised as this game https://www.igdb.com/games/castle-story--2
from my humble library

**Comment by UncleGoogle** [comment]
Hey, thanks for report.
Looks like a bug in Galaxy db. Please check the game id using from humble .log file (logs are put in %programdata%\GOG.com\Galaxy\logs) -> search for "castle" in that file until you find the name and id.

Report problem on Galaxy side: use cogwheel menu -> Report issue
- write that castle story igdb.com/games/castle-story--2 on humble platform with id: xxxx (found in log file) should be  igdb.com/games/castle-story

**Comment by UncleGoogle** [comment]
@derailedition is it fixed for you? Can I close this task?

**Comment by derailedition** [comment]
ah sorry. yes, can close it.
