### ISSUE TITLE
Provide GUI to match installed game paths.

### ISSUE THREAD

**Issue by UncleGoogle** [UncleGoogle/galaxy-integration-humblebundle#9]
Not all games can be discovered (at least on windows) #8 

Beside autodetected installed games, some of them will be still shown as uninstalled.

Ideas how to deal with the rest of games:
1. simple config file
2. open CEF GUI just after humblebundle authentication (as `NextStep`)
    - call for owned games (and local games autodetection) and then render list of games to match. 
    - problem: get_owned_games/get_local_games can lasts longer - it is better to fetch by JS. Or  - port it somehow between python and JS.
    - alternatively, scrap hb page, then do auto-detection, and then, next to game names, render buttons with linked system file prompt.
    - return answer as cookies.
3. on clicking `Install` button always show small prompt with 2 options: download or point to game exe/folder.
4. ask Galaxy to add feature where additional actions under `...` submenu can be added. Then link "point to game" there.

What do you think, community?

**Comment by UncleGoogle** [comment]
If this feature will be shipped, the game location will be handled by Galaxy window:
gogcom/galaxy-integrations-python-api/issues/58

**Comment by Danyelalejandro** [comment]
I don't know @UncleGoogle I am trying editind the congfig.ini file in order to detect installed games, but it detected just a few and not all installed games. What happened?

what are you talking about when you say: "_Installed games: use only Windows registry scan; edit search_paths to enable directory scaning feature_" I didn't find the search paths you are talking about. Thanks

**Comment by UncleGoogle** [comment]
@Danyelalejandro 
Windows registry is searched for installed games. Additionally you can define search_path in config file https://github.com/UncleGoogle/galaxy-integration-humblebundle/blob/master/src/config.ini

Then game folders defined there will be searched for subfolders with names of your owned games in humble. For example: "search_path": "C:\\Games\\Humble" will detect games placed in this folder:
- "C:\\Games\\Humble\\AnnasQuest"
- "C:\\Games\\Humble\\Obeserver"
if you owned Anna's Quest and Observer. 

It is not a proper topic for further investigation, so if you have still problem with specific game, please create an issue.

**Comment by UncleGoogle** [comment]
Closing by #83
