### ISSUE TITLE
Unable to detect "Haven Moon" as installed game

### ISSUE THREAD

**Issue by MarkoH01** [UncleGoogle/galaxy-integration-humblebundle#95]
**Describe the bug**
Downloaded the game and extracted it in a folder.
Made sure that the folder title is the same as the library title "Haven Moon - DRM free".
Game is not shown under installed humble games - I am just able to manually add it to "Others".

**Expected behavior**
GAme should be detected since the search path in config is correct and the folder name is the same as the game name shown in library.

**Plugin installed**
directly from Galaxy 

**Provide logs**
[logs.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/4456162/logs.zip)

**Comment by UncleGoogle** [comment]
Hey, thanks for the report. I don't know why, but you're right - this should be matched but is not.

You can try to remove a hypen / minus sign from the folder name and try again. Also make sure it is a hypen, not en-dash `–` or em-dash `—` or other exotic character. Let me know about the result!

**Comment by MarkoH01** [comment]
Thank you. I already tried to remove the "-" in the folder name as well as several combinations with or without space between the words. To make sure that I use the correct name I copy/pasted the Galaxy name but I just made sure that it is actually a true "minus" and not a similar looking character. Unfortunately no luck so far.

**Comment by UncleGoogle** [comment]
Ok, so it is apparently a bug in matching algorithm...
I'll try to fix this today or in the near future.

But in long term I want to provide mechanizm to match games manually and dynamically accept or reject found matches in the GUI. This will give more flexibility

**Comment by UncleGoogle** [comment]
@MarkoH01 can you extract this to`C:\Users\XXX\AppData\Local\GOG.com\Galaxy\plugins\installed\humble_f0ca3d80-a432-4d35-a9e3-60f27161ac3a\local` (replace `baseappfinder.py` file) and re-paste new logs?
[baseappfinder.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/4471891/baseappfinder.zip)

I've just added more logs on scanning, as cannot reproduce it.

**Comment by MarkoH01** [comment]
What did you do? I replaced it and the game was found - so I guess there won't be any need for more logs :)

**Comment by UncleGoogle** [comment]
heh, nothing was added to actual code, despite logging matching result. Maybe It was working al the time, but not refreshed when you tried to changed directory name. Rescan is only triggered on:
- Galaxy start
- Sync integration from Galaxy manu
- configuration file is changed

Can you paste logs anyways with the `-` in directory name? My unit tests tells me that it should be found with hypen, need to check that :)

**Comment by MarkoH01** [comment]
Ah, that might be the solution.
I renamed the folder (adding the "-" back in) and noticed that the game went away (therefore I thought it did a rescan). Then I restarted Galaxy and the game was added back. So it DOES work with the "-" but you need to restart Galaxy / resync after renaming the folder. So I guess I was the problem and not your script. Anyway it is working fine now so no need to fix something that is not broken. Sorry for the inconveniences this might have caused but thank you for your help.

**Comment by UncleGoogle** [comment]
No problem. Loosing installed game because of renamed directory is the obvious consequence of tracking exe path we both realized today. And I've added some missing unit tests that is always cool ;)

**Comment by EustaceCS** [comment]
Confirming - new baseappfinder worked for me, had problems with You Must Build A Boat title.
Thank you!
