### ISSUE TITLE
Wrong config.ini suggestions

### ISSUE THREAD

**Issue by Bertaz** [UncleGoogle/galaxy-integration-humblebundle#98]
**Describe the bug**
config.ini says that `Forward slashes are recommended` but using them makes the integration ~~crash or interpret the config wrongly (only the integration from https://github.com/UncleGoogle/galaxy-integration-humblebundle/issues/94#issuecomment-614545760 crashed)~~ revert to double backslashes or deleting the entry. Both single and double quotation marks works.

**Expected behavior**
The config comments should recommend backslashes

**Plugin installed**
directly from Galaxy and manually

**Comment by UncleGoogle** [comment]
In the latest version you should not deal with `config.ini`, the GUI should be opened, like in README.md. In logs from your other issue I can see that you've opened GUI and do not see any errors.

Can you try again to open GUI by 2-click on Install game and then paste logs and screenshot?

**Comment by Bertaz** [comment]
> In the latest version you should not deal with `config.ini`, the GUI should be opened, like in README.md. In logs from your other issue I can see that you've opened GUI and do not see any errors.

Yes, the GUI works perfectly. As you can't type paths in it directly there is no slash problem.
I opened the config to test altering the order, and thus the priority, of the libraries. Obviously it isn't a big problem as most people would use the GUI.
Still I think the config comments should recommend the same slashes the GUI is using.
